language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- wget https://github.com/pololu/fastgpio-arduino/archive/1.0.2.zip -O /tmp/fastgpio.zip
- unzip /tmp/fastgpio.zip -d /tmp/

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=micro
- BOARD=yun

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib="." --lib="/tmp/fastgpio-arduino-1.0.2/FastGPIO/" $e/*;
  done
